[package]
name = "video_record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
subprocess = "0.1.8"
systemd-journal-logger = "1.0.0"
